### ISSUE TITLE
How to handle projects with top level license and sublicenses for particular parts

### ISSUE THREAD

**Issue by nschonni** [canada-ca/ore-ero#1025]
Not sure where we can place that right now, but in theory we'll want to expand on this in the future.

_Originally posted by @ShadeWyrm in https://github.com/canada-ca/ore-ero/pull/916_

**Comment by simon332114** [comment]
Since you can already add multiple licenses per projects: adding a dropdown specifying if the license is top-level or not and an input letting you specify which part of the project is covered by the sublicense to the preset seems like it could work. I'll include a screenshot of what I mean.
![Screenshot from 2020-02-17 15-16-41](https://user-images.githubusercontent.com/46785151/74684005-9a127080-5198-11ea-91c1-fa3f578c8873.png)
![Screenshot from 2020-02-17 15-16-10](https://user-images.githubusercontent.com/46785151/74684008-9e3e8e00-5198-11ea-80ae-ea3c29bedfbd.png)

**Comment by simon332114** [comment]
To clarify, the scope section is hidden unless the sub license option is selected

**Comment by ShadeWyrm** [comment]
I'm on board with this idea, @nschonni - thoughts?
