### ISSUE TITLE
Add PR-bot build configuration to repo

### ISSUE THREAD

**Issue by smellems** [canada-ca/ore-ero#135]

**Comment by j-rewerts** [comment]
Feel free to assign me.

**Comment by j-rewerts** [comment]
Part of the work I need to do is submitting my work here in my fork back into the main repo. 

- [ ] Support CORS deployments
- [ ] Add commit author

**Comment by j-rewerts** [comment]
The creator of PRB0t has helped resolve this first one [here](https://github.com/PRB0t/PRB0t/pull/41). I still need to help test this (I'll try using Heroku).
I've got a PR open for the second one [here](https://github.com/PRB0t/PRB0t/pull/42).

**Comment by j-rewerts** [comment]
I've pinged the creator of PRB0t and I'm waiting for a response. @smellems If you'd like, I can add the current deployment for CanadaBot, which uses my fork? Then later after PRB0t proper is updated, I can switch us over?

**Comment by j-rewerts** [comment]
In the mean time, we've added our project [here](https://github.com/canada-ca/canada-bot/). @smellems and I are working together to get the Canada Bot deploying automatically from there.

**Comment by j-rewerts** [comment]
I believe the last major issue facing us is [PRB0t/44](https://github.com/PRB0t/PRB0t/issues/44), which I have a PR open for. Once that issue is resolved, we can switch to deploying just using the PRB0t repo and I'll add that info to the readme.

@smellems @fredericlestage-vdm Do we want a local PRB0t dev setup or is using the production PRB0t sufficient in local dev?

**Comment by fredericlestage-vdm** [comment]
I think having a development version is useful especially to see the logs when the PRB0T is submitting (or adding our own console.logs). It helped me figure out some of the first issues I encountered. That's why I made [this](https://github.com/fredericlestage-vdm/PRB0t) and [this](https://github.com/fredericlestage-vdm/ore-ero) forks of PRB0T and ore-ero in which I updated the READMEs with instructions on how to use them locally.

**Comment by fredericlestage-vdm** [comment]
However, I'm not sure if having a single online dev environment would be of much help, especially if there are multiple person working at the same time on it, it might get confusing as to which log is which. Too much overlap will just create more confusion.
