### ISSUE TITLE
Organization form: allow new orgs to join

### ISSUE THREAD

**Issue by j-rewerts** [canada-ca/ore-ero#150]
Similar to in #109, we need a way to submit a PR to our repo when someone wants to be added as an organization. This will probably just be a form, similar to last time.

**Comment by j-rewerts** [comment]
I think it could be worth figuring out a nice, generic way to support this kind of workflow too. We're basically doing the same thing every time. Our goal is essentially to build a web form that updates/adds to a YAML file that is used in generating the static site. If we build on top of some of the schema work done by @imadeDev and @BassamAjam, maybe we could generate the form?

**Comment by BassamAjam** [comment]
I just want to explain what we understood. You want us to create the same form of open source code in another page, but instead of generating a list of exsiting orgs, we delete it and we add 3 new fields (level of orgs, orgs name and codeOrgs).  But like that we will affect two files in the same time, the new project file and the admins file. Is it possible with your way ?

**Comment by j-rewerts** [comment]
Hey @BassamAjam. Sorry for sleeping on this issue. 

I don't think we need to modify the new project file, just the admins file.
