### ISSUE TITLE
Open Government License - Canada :: an option when submitting Open Source Code?

### ISSUE THREAD

**Issue by jethiercrc** [canada-ca/ore-ero#1646]
Greetings,

Our team would like to submit some source code to the Open Source Code on the Open Resource Exchange.

We'd like to use the "Open Government License - Canada" as our license. We found it the SPDX database (https://spdx.org/licenses/) listed as (OGL-Canada-2.0) but we don't see it in the drop-down menu in the Open Source Code Form:(https://code.open.canada.ca/en/open-source-code-form.html)

Is there some way to specify this license (or is there an equivalent?)

Thanks.

**Comment by smellems** [comment]
Hi @jethiercrc I think the OGL should not be used for source code..  The OGL is like a Creative Commons license to be used for documents, data and information.

The equivalent OSS license for code would be MIT.  See the GC Guide for Publishing Source code for other recommendations:
https://www.canada.ca/en/government/system/digital-government/digital-government-innovations/open-source-software/guide-for-publishing-open-source-code.html#toc04

Also note that the forms might not be working to submit your repo because canada-bot might be down (#1600).

You can still create a pull request with the information if you know how or let us know and we can look into adding it.
