### ISSUE TITLE
Open source software usage count is wrong for some projects

### ISSUE THREAD

**Issue by gcharest** [canada-ca/ore-ero#52]
**What**:
In the open source software [page](https://canada-ca.github.io/ore-ero/open-source-software.html), the number of Usage is wrong for some projects, including Linux, MediaWiki and Notepad++.

|Project|Displayed usage|Actual usage|
|:---|:---:|:---:|
|Linux|28|23|
|MediaWiki|5|4|
|Notepad++|8|7|

**Comment by smellems** [comment]
I think the counts are right..  I counted Notepad++ and Linux and got the correct numbers.

For MediaWiki (maybe others) it's because one department is using it more than once, but get counted only once.  It displays 5 when it could be 6..  4?

The original idea was to count how many public administrations are using it a specific OSS.

**Comment by gcharest** [comment]
It's the count of entries in the lightbox vs the table.
