### ISSUE TITLE
List software options/assessments by use case instead of by software type

### ISSUE THREAD

**Issue by thomasgohard** [canada-ca/ore-ero#6]
There's a lot of variability and different use cases within a single type of software, and one particular application may not necessarily be the best solution for all use cases. Providing a list of options by use case would likely be more useful to people.

For example, if I want to host a simple blog, a full-fledged content management system like Drupal would be overkill and add unnecessary complexity to the management of my blog versus a simple content management system tailored to blogging like Jekyll.

**Comment by smellems** [comment]
@thomasgohard the Assessments were move under the Open Source Advisory Board repo. I will close the issue here but feel free to start a conversation on the other repo.

This repo will be used to host the Github pages for the Open Resource Exchange where we will list what OSS is used and show the different option (in use) like Drupal, Jekyll, ..
