### ISSUE TITLE
Need a clear link to the GitHub project

### ISSUE THREAD

**Issue by gcharest** [canada-ca/ore-ero#796]
There seems to be no direct link to the project from the website itself (unless I totally missed it). 

I think it's important to have a clear way for external people to come over here to contribute if they want while keeping it easy for non-technical people to interact through the forms (which are awesome btw :grinning: ).

**Comment by smellems** [comment]
The only link back to Github is on the "Report a problem on this page" button at the bottom of the page and that links to Issues and is only on the homepage.

We should add another button to 'View source code and data" and have it on every page

**Comment by Tommyhudon** [comment]
You can find the project link back to github in "open source code", since the project is added to the catalog.
![image](https://user-images.githubusercontent.com/35808784/65609525-ea84f980-df7d-11e9-812f-2cfc2404dc03.png)

However we could also add a direct link on all pages. 
I would suggest to add it in the dropdown menu or maybe beside it (upper right side perhaps). What do you guys think? Which would be best in terms of design?

**Comment by smellems** [comment]
I think if we had the buttons that are on the home page on every page, we could do something like 

![image](https://user-images.githubusercontent.com/2353299/65611254-831c7900-df80-11e9-991d-f853bf43a6ca.png)

See design guide for buttons
https://wet-boew.github.io/wet-boew-styleguide/design/buttons-en.html#btn-groups
