### ISSUE TITLE
NoSQL databases as part of development tool

### ISSUE THREAD

**Issue by remyb2canada** [canada-ca/ore-ero#8]
Removing NoSQL databases all together may be limiting development tool options at the GC.

NoSQL products like MongoDB are useful during agile sprints where lots of changes occur. RDBMS are very static in nature and doesn't allow the flexibility of changes which can halt innovation. What's been suggested in the industry is use of NoSQL during agile sprinting allows to focus on the application side and figure out your data model based on your sprints. Once you have a stable product, then you're in a better position to design your SQL schema.

**Comment by smellems** [comment]
@remyb2canada the Assessments were move under the [Open Source Advisory Board](https://github.com/canada-ca/OS-Advisory_Conseil-SO) repo.  I will close the issue here but feel free to start a conversation on the other repo.

This repo will be used to host the Github pages for the Open Resource Exchange
