### ISSUE TITLE
Improve Documentation page

### ISSUE THREAD

**Issue by smellems** [canada-ca/ore-ero#94]
The documentation page needs a table of content and review to improve content and design.  Add links to Schema and Form pages for code.

https://canada-ca.github.io/ore-ero/en/docs.html

**Comment by BassamAjam** [comment]
@smellems  We've created another page for the documentation that explains how to contribute with us through the forms. So we don't need this version of the documentation anymore because it explains how to contribute with us through the github. So do you want to delete the old version of the documentation or keep it ?

**Comment by smellems** [comment]
Where is it?  Can you do a pull request? Why not update the content of the page?

**Comment by smellems** [comment]
The current documentation (more technical) will be moved back to
https://github.com/canada-ca/ore-ero/blob/master/_data/README.md

The Documentation on the site will focus on how to navigate the site to find Code and Software as well as how to use the forms to update the data.

See #633
